---
- hosts: all
  
  gather_facts: yes
  ignore_errors: true
  vars:
    user_name: serge29
    group_name: devops
  vars_files:
    - variables.yml
  tasks:
    - name: Check the time
      command: datebsgdfr
 #     when: ansible_distribution == "serge" or ansible_processor_nproc == 2
    - name: create user Serge
      user: 
        name: "{{user_name}}"
        comment: Serge Admin
    - name: create group
      group: 
        name: "{{group_name}}"
        state: present
      become: true  
    - name: Install package
      package:
        name: "{{pkg_name}}"
        state: present     